Repository jupyterhub/ltiauthenticator, pull requests merged in 2021-09, with the labels that each got.

#66 Fix release instructions by reverting to use bump2version
  _version.py
  ltiauthenticator/__init__.py
  setup.py
Labels: maintenance

#67 Add LTI 1.1 config handler for the /lti11/config route
  .gitignore
  README.md
  dev-requirements.txt
  examples/jupyterhub_config_lti11.py
  ltiauthenticator/lti11/auth.py
  ltiauthenticator/lti11/handlers.py
  ltiauthenticator/lti11/templates.py
  ltiauthenticator/tests/conftest.py
  ltiauthenticator/tests/mocking.py
  ltiauthenticator/tests/test_lti11_authenticator.py
  ltiauthenticator/tests/test_lti11_handlers.py
  ltiauthenticator/tests/test_utils.py
  ltiauthenticator/utils.py
Labels: enhancement

#69 Add changelog for 1.2.0
  CHANGELOG.md
Labels: documentation
