Repository jupyterhub/ltiauthenticator, pull requests merged in 2021-08, with the labels that each got.

#58 Rename master to main
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  CONTRIBUTING.md
  README.md
  RELEASE.md
  ltiauthenticator/lti11/validator.py
  tests/conftest.py
Labels: maintenance

#56 Update tests workflow
  .coveragerc
  .github/workflows/test.yaml
  .gitignore
  CONTRIBUTING.md
  dev-requirements.txt
  ltiauthenticator/tests/__init__.py
  ltiauthenticator/tests/conftest.py
  ltiauthenticator/tests/test_lti11_authenticator.py
  ltiauthenticator/tests/test_lti11_handlers.py
  ltiauthenticator/tests/test_lti11_validator.py
  ltiauthenticator/tests/test_utils.py
Labels: maintenance

#54 Add example LTI 1.1 configuration and readme
  .flake8
  .github/workflows/test.yaml
  .gitignore
  examples/README.md
  examples/jupyterhub_config_lti11.py
  pyproject.yaml
Labels: documentation

#59 Update release documentation and dependency
  RELEASE.md
  dev-requirements.txt
Labels: maintenance

#63 Add pyupgrade and prettier to pre-commit, and apply it
  .coveragerc
  .github/workflows/test.yaml
  .pre-commit-config.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  RELEASE.md
  _version.py
  ltiauthenticator/lti11/auth.py
  ltiauthenticator/lti11/handlers.py
  ltiauthenticator/lti11/validator.py
  ltiauthenticator/tests/conftest.py
  ltiauthenticator/tests/test_lti11_authenticator.py
  pyproject.toml
  pyproject.yaml
  setup.py
Labels: maintenance

#61 docs: initialize read-the-docs based documentation
  .github/workflows/test-docs.yaml
  .readthedocs.yml
  README.md
  docs/Makefile
  docs/README.md
  docs/make.bat
  docs/requirements.txt
  docs/source/_static/custom.css
  docs/source/_static/images/logo/favicon.ico
  docs/source/_static/images/logo/logo.png
  docs/source/conf.py
  docs/source/explanation/index.md
  docs/source/how-to/index.md
  docs/source/index.md
  docs/source/reference/index.md
  docs/source/tutorials/index.md
  test.yaml
Labels: maintenance, documentation

#62 Use pre-commit.ci to run pre-commit tests
  .github/workflows/test-package.yaml
Labels: maintenance

#60 Add changelog for 1.1.0
  CHANGELOG.md
Labels: documentation
