Repository jupyterhub/ltiauthenticator, pull requests merged in 2023-05, with the labels that each got.

#156 (docs): Document danger of user name collisions
  docs/source/lti11/getting-started.md
  docs/source/lti11/reference.md
  docs/source/lti13/getting-started.md
  docs/source/lti13/reference.md
Labels: documentation, LTI13Authenticator, LTI11Authenticator

#159 docs(lti11): Fix typo in reference
  docs/source/lti11/reference.md
Labels: documentation, LTI11Authenticator

#160 changelog for 1.5.1
  CHANGELOG.md
Labels: documentation
