Repository jupyterhub/ltiauthenticator, pull requests merged in 2023-03, with the labels that each got.

#139 Lti 1.1 make oauth_callback optional
  ltiauthenticator/lti11/constants.py
  ltiauthenticator/lti11/validator.py
  tests/lti11/conftest.py
  tests/lti11/test_lti11_validator.py
Labels: bug, LTI11Authenticator

#142 feat(lti13): Allow username key from custom claim
  README.md
  ltiauthenticator/lti13/auth.py
  ltiauthenticator/lti13/constants.py
  ltiauthenticator/lti13/error.py
  ltiauthenticator/lti13/handlers.py
  ltiauthenticator/lti13/validator.py
  tests/lti13/test_lti13_authenticator.py
  tests/lti13/test_lti13_handlers.py
  tests/lti13/test_lti13_validator.py
Labels: enhancement, LTI13Authenticator

#143 docs(lti13): Rewrite lti13 documentation
  README.md
Labels: documentation, LTI13Authenticator

#112 Fix for inconsistency in README
  README.md
  examples/jupyterhub_config_lti11.py
Labels: documentation, LTI11Authenticator

#144 Populate rdt pages
  README.md
  docs/source/conf.py
  docs/source/explanation/index.md
  docs/source/how-to/index.md
  docs/source/index.md
  docs/source/lti11/getting-started.md
  docs/source/lti11/index.md
  docs/source/lti11/lms-integration.md
  docs/source/lti11/reference.md
  docs/source/lti13/getting-started.md
  docs/source/lti13/index.md
  docs/source/lti13/lms-integration.md
  docs/source/lti13/reference.md
  docs/source/reference/index.md
  docs/source/tutorials/index.md
Labels: documentation

#145 Add changelog for 1.5.0
  CHANGELOG.md
Labels: documentation
