Repository jupyterhub/ltiauthenticator, pull requests merged in 2023-06, with the labels that each got.

#161 docs: fix details in changelog - missing date, heading level, links
  CHANGELOG.md
Labels: documentation

#166 feat: Allow to manually specify URL scheme
  docs/source/lti11/getting-started.md
  docs/source/lti11/reference.md
  docs/source/lti13/getting-started.md
  docs/source/lti13/reference.md
  ltiauthenticator/lti11/auth.py
  ltiauthenticator/lti11/handlers.py
  ltiauthenticator/lti13/auth.py
  ltiauthenticator/lti13/handlers.py
  ltiauthenticator/utils.py
  tests/lti11/test_lti11_authenticator.py
  tests/lti13/test_lti13_authenticator.py
  tests/test_utils.py
Labels: enhancement

#164 maint: Ditch dependency to OAuthenticator
  ltiauthenticator/lti11/auth.py
  ltiauthenticator/lti11/handlers.py
  ltiauthenticator/lti11/validator.py
  ltiauthenticator/lti13/auth.py
  ltiauthenticator/lti13/handlers.py
  ltiauthenticator/utils.py
  pyproject.toml
  tests/conftest.py
  tests/lti11/conftest.py
  tests/lti11/mocking.py
  tests/lti13/conftest.py
  tests/lti13/mocking.py
  tests/lti13/stash_of_unused_fixtures.py
  tests/lti13/test_lti13_handlers.py
Labels: maintenance

#167 Add changelog for 1.6.1
  CHANGELOG.md
Labels: documentation

#168 docs: fix uri_scheme default value
  docs/source/lti11/reference.md
  docs/source/lti13/reference.md
Labels: documentation
