Repository jupyterhub/ltiauthenticator, pull requests merged in 2024-01, with the labels that each got.

#185 Fix build with hatchling backend
  pyproject.toml
Labels: bug

#186 ci: test against python 3.12
  .github/workflows/test-package.yaml
Labels: ci

#187 ci: pin robust github action to major version only
  .github/workflows/publish.yaml
Labels: ci

#189 docs: Confine type of client_id to list[str] or set[str]
  .pre-commit-config.yaml
  docs/source/lti13/getting-started.md
  docs/source/lti13/reference.md
  examples/jupyterhub_config_lti13.py
Labels: documentation

#188 Add changelog for 1.6.2
  CHANGELOG.md
Labels: documentation
